[package]
name = "shrimp-checker"
version = "0.1.5"
edition = "2024"
rust-version = "1.88"
description = "A lightweight desktop GUI app that checks whether you are a shrimp"
license = "MIT"
repository = "https://github.com/wielorzeczownik/shrimp-checker"
readme = "README.md"
keywords = ["shrimp", "meme", "gui", "desktop", "iced", "sigma", "check"]
categories = ["gui"]

[dependencies]
iced = { version = "0.14.0", features = ["image"] }
rodio = "0.22.2"
sys-locale = "0.3.2"

[profile.release]
opt-level = "s"
lto = "thin"
codegen-units = 1
strip = "symbols"
panic = "abort"
